import { lazy } from "react";

export const Tracker = lazy(() => import("../components/Tracker.jsx"));
export const Ledger = lazy(() => import("../components/Ledger.jsx"));
export const LiveScanner = lazy(() => import("../components/LiveScanner.jsx"));
export const TaxesEstimatorWrapper = lazy(() => import("../components/TaxesEstimator.jsx"));
export const AIActionPlan = lazy(() => import("../components/AIActionPlan.jsx").then(m => ({ default: m.AIActionPlan })));
export const StackBuilder = lazy(() => import("../components/StackBuilder.jsx").then(m => ({ default: m.StackBuilder })));
export const PricingPage = lazy(() => import("../components/PricingPage.jsx").then(m => ({ default: m.PricingPage })));
export const PromoChat = lazy(() => import("../components/PromoChat.jsx"));
export const PromoAdvisorPanel = lazy(() => import("../components/PromoAdvisorPanel.jsx").then(m => ({ default: m.PromoAdvisorPanel })));
export const PromoIntakeRoute = lazy(() => import("../routes/PromoIntakeRoute.jsx"));
export const LandingRoute = lazy(() => import("../routes/LandingRoute.jsx"));
export const FeatureFlagAdmin = lazy(() => import("../components/FeatureFlagAdmin.jsx"));
export const TrackInsights = lazy(() => import("../components/TrackInsights.jsx"));
export const DailyBriefPage = lazy(() => import("../components/dashboard/DailyBriefPage.jsx"));
export const DailyDashboard = lazy(() => import("../components/dashboard/DailyDashboard.jsx"));
export const CommunityPromoBoard = lazy(() => import("../components/CommunityPromoBoard.jsx"));
export const SmartPromoRecommender = lazy(() => import("../components/dashboard/SmartPromoRecommender.jsx"));
export const PromoCalendar = lazy(() => import("../components/PromoCalendar.jsx"));
export const ReferralHub = lazy(() => import("../components/ReferralHub.jsx"));
export const CompetitorComparison = lazy(() => import("../components/CompetitorComparison.jsx"));
export const TeamAccounts = lazy(() => import("../components/TeamAccounts.jsx"));
export const BonusBet = lazy(() => import("../calculators/BonusBet.jsx"));
export const ProfitBoost = lazy(() => import("../calculators/ProfitBoost.jsx"));
export const FirstBet = lazy(() => import("../calculators/FirstBet.jsx"));
export const DepositMatch = lazy(() => import("../calculators/DepositMatch.jsx"));
export const NoVig = lazy(() => import("../calculators/NoVig.jsx"));
export const NoVig3Way = lazy(() => import("../calculators/NoVig3Way.jsx"));
export const PlusEV = lazy(() => import("../calculators/PlusEV.jsx"));
export const Arb2Way = lazy(() => import("../calculators/Arb2Way.jsx"));
export const Arb3Way = lazy(() => import("../calculators/Arb3Way.jsx"));
export const ParlayHedge = lazy(() => import("../calculators/ParlayHedge.jsx"));
export const KellyCriterion = lazy(() => import("../calculators/KellyCriterion.jsx"));
export const InsurancePromo = lazy(() => import("../calculators/InsurancePromo.jsx"));
export const TeaserCalc = lazy(() => import("../calculators/TeaserCalc.jsx"));
export const RoundRobinCalc = lazy(() => import("../calculators/RoundRobinCalc.jsx"));
export const ParlayBuilder = lazy(() => import("../calculators/ParlayBuilder.jsx"));
export const SGPEstimator = lazy(() => import("../calculators/SGPEstimator.jsx"));
export const HoldCalc = lazy(() => import("../calculators/HoldCalc.jsx"));
export const BetSizingAdvisor = lazy(() => import("../calculators/BetSizingAdvisor.jsx"));
export const LineShop = lazy(() => import("../calculators/LineShop.jsx"));
export const GetStartedRoute = lazy(() => import("../routes/HomeRoutes.jsx").then(m => ({ default: m.GetStartedRoute })));
export const WhatsNewRoute = lazy(() => import("../routes/HomeRoutes.jsx").then(m => ({ default: m.WhatsNewRoute })));
export const AboutRoute = lazy(() => import("../routes/HomeRoutes.jsx").then(m => ({ default: m.AboutRoute })));
