const VALIDATION_COMMANDS = Object.freeze({
  smokeCommand: { label: "Repo launch smoke", command: "npm run smoke:launch" },
  browserSmoke: { label: "Browser smoke", command: "npm run smoke:browser" },
  tests: { label: "Vitest", command: "npm test" },
  build: { label: "Build", command: "npm run build" },
});

function isRecord(value) {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

export function normalizeValidationState(value) {
  const status = String(value || "").trim().toLowerCase();
  if (/^(?:(?:\d+\/\d+)\s+)?(?:passing|passed|green)\b/.test(status)) return "passing";
  if (/^(?:failing|failed|red|blocked)\b/.test(status)) return "failing";
  if (/^(?:warning|partial|stale|skipped)\b/.test(status)) return "warning";
  return "unknown";
}

function receiptLabel(state, observedAt) {
  if (state === "unknown") return "unknown · no command-addressed receipt";
  return `${state} · verified ${observedAt || "date unknown"}`;
}

function commandReceipt(surfaces, key, status) {
  const spec = VALIDATION_COMMANDS[key];
  if (key === "tests") {
    const passing = Number.isFinite(status.testsPassing) ? status.testsPassing : null;
    const total = Number.isFinite(status.testsTotal) ? status.testsTotal : null;
    const observedAt = status.testsLastRun || null;
    if (passing != null && total != null && observedAt) {
      const state = passing === total ? "passing" : "failing";
      return {
        ...spec,
        state,
        observedAt,
        exitCode: state === "passing" ? 0 : null,
        commitSha: null,
        source: "context/PROJECT_STATUS.json#tests",
        lastKnown: `${passing}/${total} ${state} · verified ${observedAt}`,
      };
    }
  }

  const surface = surfaces.find((item) => String(item?.command || "").trim() === spec.command);
  if (!surface) {
    return {
      ...spec,
      state: "unknown",
      observedAt: null,
      exitCode: null,
      commitSha: null,
      source: "context/PROJECT_STATUS.json#testingSurfaces",
      lastKnown: receiptLabel("unknown", null),
    };
  }
  const state = normalizeValidationState(surface.status);
  const observedAt = surface.observedAt || surface.verifiedAt || surface.lastRun || status.lastUpdated || null;
  return {
    ...spec,
    state,
    observedAt,
    exitCode: Number.isInteger(surface.exitCode) ? surface.exitCode : null,
    commitSha: surface.commitSha || null,
    source: "context/PROJECT_STATUS.json#testingSurfaces",
    lastKnown: receiptLabel(state, observedAt),
  };
}

export function buildProjectStatusMirror(status) {
  if (!isRecord(status)) throw new Error("PROJECT_STATUS must be a JSON object");
  const surfaces = Array.isArray(status.testingSurfaces) ? status.testingSurfaces : [];
  return {
    schemaVersion: "2.0",
    source: "context/PROJECT_STATUS.json",
    sourceLastUpdated: status.lastUpdated || null,
    testsPassing: Number.isFinite(status.testsPassing) ? status.testsPassing : null,
    testsTotal: Number.isFinite(status.testsTotal) ? status.testsTotal : null,
    testsLastRun: status.testsLastRun || null,
    validation: Object.fromEntries(
      Object.keys(VALIDATION_COMMANDS).map((key) => [key, commandReceipt(surfaces, key, status)]),
    ),
  };
}

export function validateLaunchProofPayload(payload) {
  if (!isRecord(payload)) throw new Error("LAUNCH_PROOFS must be a JSON object");
  if (typeof payload.schemaVersion !== "string" || !payload.schemaVersion.trim()) {
    throw new Error("LAUNCH_PROOFS.schemaVersion must be a non-empty string");
  }
  if (!isRecord(payload.proofs)) throw new Error("LAUNCH_PROOFS.proofs must be an object");
  for (const [key, proof] of Object.entries(payload.proofs)) {
    if (!isRecord(proof)) throw new Error(`LAUNCH_PROOFS.proofs.${key} must be an object`);
    if (typeof proof.status !== "string" || !proof.status.trim()) {
      throw new Error(`LAUNCH_PROOFS.proofs.${key}.status must be a non-empty string`);
    }
    if (proof.criteria != null && !Array.isArray(proof.criteria)) {
      throw new Error(`LAUNCH_PROOFS.proofs.${key}.criteria must be an array`);
    }
    if (proof.receipts != null && !Array.isArray(proof.receipts)) {
      throw new Error(`LAUNCH_PROOFS.proofs.${key}.receipts must be an array`);
    }
  }
  return payload;
}

export function renderGeneratedExport({ banner, exportName, payload }) {
  return [
    `// Generated by ${banner}.`,
    "// Do not edit by hand; update the canonical context source instead.",
    `export const ${exportName} = ${JSON.stringify(payload, null, 2)};`,
    "",
  ].join("\n");
}
