import fs from 'node:fs';
import path from 'node:path';
import { compileVisualQaReceipt } from './visual-qa-receipt.mjs';

export function compileReleaseParity({ root, visualReceipt, testEvidence = null }) {
  const receiptDir = path.join(root, 'docs', 'visual-qa');
  const verified = compileVisualQaReceipt(visualReceipt, { receiptDir, now: new Date(visualReceipt.capturedAt) });
  const hasConfig = fs.existsSync(path.join(root, 'capacitor.config.ts')) || fs.existsSync(path.join(root, 'capacitor.config.js'));
  const nativeProjects = ['ios', 'android'].filter((name) => fs.existsSync(path.join(root, name)));
  const nativeState = nativeProjects.length ? 'active' : hasConfig ? 'planned-no-native-projects' : 'browser-only';
  return {
    schemaVersion: '1.0',
    generatedAt: verified.capturedAt,
    visual: {
      capturedAt: verified.capturedAt,
      themes: verified.themes,
      captures: verified.captures,
      reviewed: true,
      blockingDefectsOpen: 0,
    },
    tests: testEvidence?.success ? {
      state: 'green',
      files: testEvidence.files,
      assertions: testEvidence.assertions,
      receiptSha256: testEvidence.reportSha256,
    } : { state: 'unavailable' },
    native: { state: nativeState, projects: nativeProjects },
  };
}

export function renderReleaseParity(payload) {
  const lines = [
    '# Release Parity Evidence', '',
    `> Generated from typed receipts: ${payload.generatedAt} · visual ${payload.visual.reviewed ? 'inspected' : 'unreviewed'} · defects ${payload.visual.blockingDefectsOpen}`, '',
    '## Browser matrix', '',
    '| Viewport | Theme | Artifact | SHA-256 |', '|---|---|---|---|',
    ...payload.visual.captures.map((c) => `| ${c.viewport.width} × ${c.viewport.height} | ${c.theme} | \`${c.file}\` | \`${c.sha256}\` |`),
    '', '## Evidence state', '',
    `- Pixel inspection: **${payload.visual.reviewed ? 'COMPLETE' : 'INCOMPLETE'}** · blocking defects: ${payload.visual.blockingDefectsOpen}`,
    `- Tests: **${payload.tests.state.toUpperCase()}**${payload.tests.files ? ` · ${payload.tests.files.passing}/${payload.tests.files.total} files · ${payload.tests.assertions.passing}/${payload.tests.assertions.total} assertions` : ''}`,
    `- Native applicability: **${payload.native.state}**${payload.native.projects.length ? ` · ${payload.native.projects.join(', ')}` : ''}`,
    '', 'Native parity is not claimed from Capacitor configuration alone; an iOS or Android project directory plus rendered evidence is required.',
    '', '*Generated by `scripts/render-release-parity.mjs` from `docs/visual-qa/LATEST.json` and `audits/test-evidence-latest.json`.*', '',
  ];
  return lines.join('\n');
}
