#!/bin/bash
# configure-r2-backup.sh — Wire Cloudflare R2 credentials into the Hetzner backup script.
#
# Run this ON the Hetzner server (178.156.211.100) after obtaining R2 credentials:
#   ssh root@178.156.211.100 "bash -s" < scripts/configure-r2-backup.sh
#
# Or run interactively:
#   ssh root@178.156.211.100
#   bash /tmp/configure-r2-backup.sh
#
# Prerequisites:
#   - Cloudflare R2 bucket "studio-backups" created
#   - R2 API token generated with Object Write permissions
#   - Account ID from Cloudflare dashboard → R2 → Settings
set -euo pipefail

BACKUP_SCRIPT="/opt/studio/scripts/backup.sh"
CONFIG_FILE="/opt/studio/.r2-config"

echo "╔══════════════════════════════════════════════════╗"
echo "║  R2 Backup Configuration                         ║"
echo "╚══════════════════════════════════════════════════╝"

if [[ ! -f "$BACKUP_SCRIPT" ]]; then
  echo "✗ backup.sh not found at $BACKUP_SCRIPT — run server-setup-phase4.sh first"
  exit 1
fi

# Prompt for credentials if not already set via env
R2_ACCOUNT_ID="${R2_ACCOUNT_ID:-}"
R2_ACCESS_KEY="${R2_ACCESS_KEY:-}"
R2_SECRET_KEY="${R2_SECRET_KEY:-}"
R2_BUCKET="${R2_BUCKET:-studio-backups}"

if [[ -z "$R2_ACCOUNT_ID" ]]; then
  read -rp "Cloudflare Account ID: " R2_ACCOUNT_ID
fi
if [[ -z "$R2_ACCESS_KEY" ]]; then
  read -rp "R2 Access Key ID: " R2_ACCESS_KEY
fi
if [[ -z "$R2_SECRET_KEY" ]]; then
  read -rsp "R2 Secret Access Key: " R2_SECRET_KEY
  echo
fi
if [[ -z "$R2_BUCKET" ]]; then
  read -rp "R2 Bucket name [studio-backups]: " R2_BUCKET
  R2_BUCKET="${R2_BUCKET:-studio-backups}"
fi

R2_ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"

# Write credentials to config file (chmod 600)
cat > "$CONFIG_FILE" <<EOF
# Cloudflare R2 backup credentials
# Generated by configure-r2-backup.sh — do not commit
R2_BUCKET="${R2_BUCKET}"
R2_ENDPOINT="${R2_ENDPOINT}"
R2_ACCESS_KEY="${R2_ACCESS_KEY}"
R2_SECRET_KEY="${R2_SECRET_KEY}"
EOF
chmod 600 "$CONFIG_FILE"
echo "✓ Credentials written to $CONFIG_FILE (chmod 600)"

# Rewrite backup.sh to source from config file instead of hardcoded values
cat > "$BACKUP_SCRIPT" <<'SCRIPT'
#!/bin/bash
set -euo pipefail

CONFIG_FILE="/opt/studio/.r2-config"
if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "✗ R2 config not found at $CONFIG_FILE — run configure-r2-backup.sh first"
  exit 1
fi
# shellcheck source=/dev/null
source "$CONFIG_FILE"

TIMESTAMP=$(date -u +%Y-%m-%dT%H-%M-%SZ)
BACKUP_DIR="/opt/studio/backups"
mkdir -p "$BACKUP_DIR"

# Check awscli is installed
if ! command -v aws &>/dev/null; then
  echo "✗ awscli not installed — run: pip3 install awscli"
  exit 1
fi

SUCCESS=0
FAIL=0

for project_dir in /opt/studio/projects/supabase-*/; do
  [[ -d "$project_dir" ]] || continue
  project=$(basename "$project_dir" | sed 's/supabase-//')
  env_file="$project_dir/.env"

  if [[ ! -f "$env_file" ]]; then
    echo "⚠ Skipping $project — no .env file"
    continue
  fi

  pg_password=$(grep '^POSTGRES_PASSWORD=' "$env_file" | cut -d= -f2-)
  pg_port=$(grep '^POSTGRES_PORT=' "$env_file" 2>/dev/null | cut -d= -f2- || echo 5432)

  if [[ -z "$pg_password" ]]; then
    echo "⚠ Skipping $project — POSTGRES_PASSWORD not found in .env"
    continue
  fi

  backup_file="${BACKUP_DIR}/${project}_${TIMESTAMP}.dump"
  echo "→ Backing up $project (port $pg_port)..."

  if PGPASSWORD="$pg_password" pg_dump \
      -h localhost -p "$pg_port" -U postgres postgres \
      -Fc -f "$backup_file" 2>/dev/null; then

    if AWS_ACCESS_KEY_ID="$R2_ACCESS_KEY" \
       AWS_SECRET_ACCESS_KEY="$R2_SECRET_KEY" \
       aws s3 cp "$backup_file" \
         "s3://${R2_BUCKET}/${project}/${TIMESTAMP}.dump" \
         --endpoint-url "$R2_ENDPOINT" \
         --quiet 2>/dev/null; then
      rm "$backup_file"
      echo "  ✓ $project → R2 (${TIMESTAMP}.dump)"
      ((SUCCESS++))
    else
      echo "  ✗ $project — R2 upload failed (dump kept at $backup_file)"
      ((FAIL++))
    fi
  else
    echo "  ✗ $project — pg_dump failed"
    ((FAIL++))
  fi
done

echo ""
echo "Backup complete: ${TIMESTAMP}"
echo "  ✓ ${SUCCESS} succeeded  ✗ ${FAIL} failed"

if [[ $FAIL -gt 0 ]]; then
  exit 1
fi
SCRIPT

chmod +x "$BACKUP_SCRIPT"
echo "✓ backup.sh rewritten to use $CONFIG_FILE"

# Verify the cron job exists
if ! crontab -l 2>/dev/null | grep -q "backup.sh"; then
  (crontab -l 2>/dev/null; echo "0 3 * * * /opt/studio/scripts/backup.sh >> /var/log/studio-backup.log 2>&1") | crontab -
  echo "✓ Daily cron job added (runs at 03:00 UTC)"
else
  echo "✓ Daily cron job already configured"
fi

# Verify awscli
if ! command -v aws &>/dev/null; then
  echo "⚠ awscli not installed — installing..."
  pip3 install awscli --quiet && echo "✓ awscli installed"
fi

# Test the connection
echo ""
echo "Testing R2 connection..."
if AWS_ACCESS_KEY_ID="$R2_ACCESS_KEY" \
   AWS_SECRET_ACCESS_KEY="$R2_SECRET_KEY" \
   aws s3 ls "s3://${R2_BUCKET}/" \
     --endpoint-url "$R2_ENDPOINT" &>/dev/null; then
  echo "✓ R2 connection successful — bucket '${R2_BUCKET}' is accessible"
  echo ""
  echo "  Backup is ready. It will run daily at 03:00 UTC."
  echo "  Test manually: /opt/studio/scripts/backup.sh"
  echo "  View logs:     tail -f /var/log/studio-backup.log"
else
  echo "⚠ R2 connection test failed — check credentials and bucket name"
  echo "  Credentials saved at $CONFIG_FILE"
  echo "  Endpoint: $R2_ENDPOINT"
  echo "  Bucket:   $R2_BUCKET"
  exit 1
fi
