#!/usr/bin/env node
// configure-beacon.mjs — Auto-configure Active Session Beacon for all studioOsApplied repos.
// Reads the Gist ID from Hub Settings or env, looks up each project's id from
// studioRegistry.js, then writes .claude/beacon.env to each local repo.
//
// Usage:
//   node scripts/configure-beacon.mjs --gist-id <GIST_ID>
//   BEACON_GIST_ID=<id> node scripts/configure-beacon.mjs
//   node scripts/configure-beacon.mjs --dry-run    # preview without writing
//   node scripts/configure-beacon.mjs --project <slug>  # single project

import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..');
const registry = JSON.parse(fs.readFileSync(path.join(root, 'portfolio', 'PROJECT_REGISTRY.json'), 'utf8'));

const DRY_RUN   = process.argv.includes('--dry-run');
const TARGET    = (() => { const i = process.argv.indexOf('--project'); return i >= 0 ? process.argv[i + 1] : null; })();
const GIST_ARG  = (() => { const i = process.argv.indexOf('--gist-id'); return i >= 0 ? process.argv[i + 1] : null; })();

// ── Resolve Gist ID ───────────────────────────────────────────────────────────
let BEACON_GIST_ID = GIST_ARG || process.env.BEACON_GIST_ID || '';

// Try to auto-discover from existing beacon.env in studio-ops
if (!BEACON_GIST_ID) {
  const selfBeacon = path.join(root, '.claude', 'beacon.env');
  if (fs.existsSync(selfBeacon)) {
    const content = fs.readFileSync(selfBeacon, 'utf8');
    const match = content.match(/BEACON_GIST_ID=(.+)/);
    if (match) BEACON_GIST_ID = match[1].trim();
  }
}

if (!BEACON_GIST_ID) {
  console.error('\n  ✗ No BEACON_GIST_ID provided.');
  console.error('  Options:');
  console.error('    1. node scripts/configure-beacon.mjs --gist-id <id>');
  console.error('    2. BEACON_GIST_ID=<id> node scripts/configure-beacon.mjs');
  console.error('    3. Create .claude/beacon.env in this repo with BEACON_GIST_ID=<id>');
  console.error('  Get the Gist ID from: Hub Settings → Active Session Beacon\n');
  process.exit(1);
}

// ── Load project IDs from studioRegistry.js ──────────────────────────────────
// Try to read Hub's studioRegistry.js locally if available
let hubProjectIds = {};
const hubRegPath = path.join(root, '..', 'vaultspark-studio-hub', 'src', 'data', 'studioRegistry.js');
if (fs.existsSync(hubRegPath)) {
  try {
    const src = fs.readFileSync(hubRegPath, 'utf8');
    const re = /\{([^{}]*)\}/g;
    let match;
    while ((match = re.exec(src)) !== null) {
      const block = match[1];
      const idMatch = block.match(/id:\s*['"]([^'"]+)['"]/);
      if (idMatch) hubProjectIds[idMatch[1]] = idMatch[1];
    }
  } catch { /* studioRegistry.js unreadable — fall back to slug */ }
}

console.log('\n╔══════════════════════════════════════════════════════╗');
console.log('║  BEACON AUTO-CONFIGURE                               ║');
console.log(`╚══════════════════════════════════════════════════════╝${DRY_RUN ? '  [DRY RUN]' : ''}\n`);
console.log(`  Gist ID: ${BEACON_GIST_ID}\n`);

let written = 0, skipped = 0, errors = 0;

for (const project of registry.projects) {
  if (project.status === 'archived') continue;
  if (!project.studioOsApplied) continue;
  if (!project.localPath) continue;
  if (TARGET && project.slug !== TARGET) continue;
  if (!fs.existsSync(project.localPath)) {
    console.log(`  ⊘ ${project.slug} — localPath not found (${project.localPath})`);
    skipped++;
    continue;
  }

  const claudeDir = path.join(project.localPath, '.claude');
  const beaconPath = path.join(claudeDir, 'beacon.env');

  // Determine project ID (Hub uses slug as id by default)
  const projectId = hubProjectIds[project.slug] || project.slug;

  const content = `# Active Session Beacon configuration
# Generated by scripts/configure-beacon.mjs — do not commit (add to .gitignore)
BEACON_GIST_ID=${BEACON_GIST_ID}
BEACON_PROJECT_ID=${projectId}
`;

  if (DRY_RUN) {
    console.log(`  → ${project.slug}: would write .claude/beacon.env (project_id=${projectId})`);
    written++;
    continue;
  }

  try {
    if (!fs.existsSync(claudeDir)) fs.mkdirSync(claudeDir, { recursive: true });

    // Don't overwrite if already configured with same values
    if (fs.existsSync(beaconPath)) {
      const existing = fs.readFileSync(beaconPath, 'utf8');
      if (existing.includes(`BEACON_GIST_ID=${BEACON_GIST_ID}`) && existing.includes(`BEACON_PROJECT_ID=${projectId}`)) {
        console.log(`  ✓ ${project.slug}: already configured`);
        skipped++;
        continue;
      }
    }

    fs.writeFileSync(beaconPath, content);

    // Ensure .claude/beacon.env is in .gitignore
    const gitignorePath = path.join(project.localPath, '.gitignore');
    const gitignoreEntry = '.claude/beacon.env';
    if (fs.existsSync(gitignorePath)) {
      const gi = fs.readFileSync(gitignorePath, 'utf8');
      if (!gi.includes(gitignoreEntry)) {
        fs.appendFileSync(gitignorePath, `\n${gitignoreEntry}\n`);
        console.log(`  ✓ ${project.slug}: beacon.env written + added to .gitignore`);
      } else {
        console.log(`  ✓ ${project.slug}: beacon.env written (.gitignore already has entry)`);
      }
    } else {
      fs.writeFileSync(gitignorePath, `${gitignoreEntry}\n`);
      console.log(`  ✓ ${project.slug}: beacon.env written + .gitignore created`);
    }
    written++;
  } catch (e) {
    console.error(`  ✗ ${project.slug}: ${e.message}`);
    errors++;
  }
}

console.log(`\n  Written: ${written}  Already configured: ${skipped}  Errors: ${errors}`);
if (DRY_RUN) console.log('  (Dry run — no files written)');
else if (written > 0) {
  console.log('\n  Beacon is ready. Each project start.md Phase 0 will activate it.');
  console.log('  The Stop hook clears the beacon on session end.');
  console.log(`\n  Test: open any repo in Claude Code, say \`start\`, then check`);
  console.log(`        https://gist.github.com/${BEACON_GIST_ID}\n`);
}
